<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\CourseCategory;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = CourseCategory::all()->keyBy('slug');

        $courses = [
            [
                'name' => 'IELTS Preparation for Band 7 Goal',
                'badge_text' => 'Test Prep',
                'slug' => 'ielts-masterclass',
                'category_slug' => 'study-abroad-test-prep',
                'description' => 'Planning abroad and unsure how to prepare for IELTS? This course gives students a weekly plan with mock tests, writing correction, speaking practice, and instructor feedback. Best for students who want to understand their test path before paying for applications or documents.',
                'course_outline' => "IELTS format and scoring\nListening strategy and note-taking\nReading speed and accuracy\nWriting Task 1 and Task 2 structures\nSpeaking confidence labs\nWeekly mock tests and score review\nDestination and timeline planning",
                'photo' => 'site/img/ielts-preparation.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '15 Seats',
                'duration' => '6 Weeks',
                'instructor' => 'Aakash Subedi',
                'is_featured' => true,
                'meta_keywords' => 'IELTS Pokhara, IELTS preparation Nepal, Band 7 IELTS',
            ],
            [
                'name' => 'PTE Academic Preparation',
                'badge_text' => 'Fast Track',
                'slug' => 'pte-elite-training',
                'category_slug' => 'study-abroad-test-prep',
                'description' => 'Need computer-based English test preparation? This PTE course focuses on the test interface, timing, fluency, templates, and mock analysis. Best for students who need structured weekly practice instead of random self-study.',
                'course_outline' => "PTE test interface\nAI scoring essentials\nSpeaking fluency drills\nWriting templates\nReading and listening practice\nMock test analysis\nScore improvement plan",
                'photo' => 'site/img/pte-preparation.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '10 Seats',
                'duration' => '6 Weeks',
                'instructor' => 'Aakash Subedi',
                'is_featured' => true,
                'meta_keywords' => 'PTE Pokhara, PTE class Nepal, PTE Academic training',
            ],
            [
                'name' => 'Japanese Proficiency JLPT N5',
                'badge_text' => 'Japan Pathway',
                'slug' => 'jlpt-n5-elite',
                'category_slug' => 'language-classes',
                'description' => 'Starting Japanese from zero? JLPT N5 gives students a foundation in Hiragana, Katakana, basic Kanji, grammar, listening, and simple conversation. Best for students who want structure before moving into higher JLPT levels or Japan-related study and work preparation.',
                'course_outline' => "Hiragana and Katakana\nN5 vocabulary and grammar\nBasic Kanji\nListening and conversation practice\nJapanese culture and etiquette\nJLPT mock preparation",
                'photo' => 'site/img/jlpt-n5.jpg',
                'price' => 'Rs. 15,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '15 Seats',
                'duration' => '6 Months',
                'instructor' => 'Navaraj Thapa',
                'is_featured' => true,
                'meta_keywords' => 'JLPT N5 Pokhara, Japanese class Nepal, Japan language course',
            ],
            [
                'name' => 'Japanese Proficiency JLPT N4',
                'badge_text' => 'Language Plus',
                'slug' => 'jlpt-n4',
                'category_slug' => 'language-classes',
                'description' => 'Already know basic Japanese but need more structure? JLPT N4 builds vocabulary, Kanji, grammar, reading, and listening so learners can understand everyday Japanese more clearly.',
                'course_outline' => "N4 grammar patterns\nExpanded vocabulary\nKanji practice\nReading short passages\nListening comprehension\nConversation drills\nJLPT preparation strategy",
                'photo' => 'site/img/jlpt-n4.jpg',
                'price' => 'Rs. 13,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '15 Seats',
                'duration' => '3 Months',
                'instructor' => 'Navaraj Thapa',
                'is_featured' => false,
                'meta_keywords' => 'JLPT N4 Pokhara, Japanese language Nepal',
            ],
            [
                'name' => 'Korean EPS-TOPIK Preparation',
                'badge_text' => 'EPS-TOPIK',
                'slug' => 'professional-korean-eps',
                'category_slug' => 'language-classes',
                'description' => 'Preparing for EPS-TOPIK but unsure where to start? This program gives learners a structured Korean study route with Hangul, high-frequency vocabulary, listening, reading, and exam-style practice for work-focused applicants.',
                'course_outline' => "Hangul foundation\nEPS vocabulary\nListening drills\nReading comprehension\nIndustry terms\nMock tests\nApplication timeline planning",
                'photo' => 'site/img/eps-topik.jpg',
                'price' => 'Rs. 18,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '40 Seats',
                'duration' => '6 Months',
                'instructor' => 'Pradeep Paudel',
                'is_featured' => true,
                'meta_keywords' => 'Korean class Pokhara, EPS TOPIK Nepal, Korean language',
            ],
            [
                'name' => 'Basic Korean Course',
                'badge_text' => 'Beginner Friendly',
                'slug' => 'basic-korean-course',
                'category_slug' => 'language-classes',
                'description' => 'Want to learn Korean without feeling lost in the alphabet? This beginner course helps learners read Hangul, speak simple sentences, understand daily vocabulary, and build the base needed for culture, study, or future EPS-TOPIK preparation.',
                'course_outline' => "Hangul reading and writing\nBasic vocabulary\nSimple sentence patterns\nDaily conversation\nListening practice\nKorean culture basics",
                'photo' => 'site/img/basic-korean.jpg',
                'price' => 'Rs. 10,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '40 Seats',
                'duration' => '3 Months',
                'instructor' => 'Pradeep Paudel',
                'is_featured' => false,
                'meta_keywords' => 'basic Korean Pokhara, Korean language Nepal',
            ],
            [
                'name' => 'Practical English Communication',
                'badge_text' => 'Communication',
                'slug' => 'global-english-pro',
                'category_slug' => 'language-classes',
                'description' => 'If English is difficult during interviews, presentations, class participation, or daily communication, this course focuses on practical speaking, writing, correction, and presentation habits.',
                'course_outline' => "Grammar correction\nSpeaking confidence\nPublic speaking\nProfessional writing\nInterview practice\nPresentation skills\nCross-cultural communication",
                'photo' => 'site/img/advanced-english.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '15 Seats',
                'duration' => '45 Days',
                'instructor' => 'Ajay B.K.',
                'is_featured' => true,
                'meta_keywords' => 'English speaking Pokhara, professional English Nepal',
            ],
            [
                'name' => 'Basic English Foundation',
                'badge_text' => 'Foundation',
                'slug' => 'basic-english-course',
                'category_slug' => 'language-classes',
                'description' => 'Starting English again from the basics? This foundation course rebuilds grammar, vocabulary, reading, writing, listening, and everyday speaking so learners can stop guessing and start communicating with confidence.',
                'course_outline' => "English basics\nVocabulary building\nGrammar foundations\nListening comprehension\nReading practice\nWriting practice\nDaily speaking drills",
                'photo' => 'site/img/basic-english.jpg',
                'price' => 'Rs. 5,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '15 Seats',
                'duration' => '45 Days',
                'instructor' => 'Ajay B.K.',
                'is_featured' => false,
                'meta_keywords' => 'basic English Pokhara, English course Nepal',
            ],
            [
                'name' => 'Web Development with Laravel Basics',
                'badge_text' => 'Project-Based',
                'slug' => 'professional-web-development',
                'category_slug' => 'web-development-it-career',
                'description' => 'Want a web skill you can show through projects? This course helps beginners practice HTML, CSS, responsive UI, Laravel, databases, APIs, and deployment basics. Best for learners who want practical outputs, not only theory.',
                'course_outline' => "HTML and CSS foundations\nResponsive UI basics\nLaravel MVC architecture\nRouting and middleware\nDatabase design\nAuthentication concepts\nREST API fundamentals\nLive project deployment",
                'photo' => 'site/img/basic-web-development.jpg',
                'price' => 'Rs. 24,850',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '10 Seats',
                'duration' => '3 Months',
                'instructor' => 'Prasun Paudel',
                'is_featured' => true,
                'meta_keywords' => 'web development Pokhara, Laravel course Nepal, coding course',
            ],
            [
                'name' => 'Advanced Diploma in Computer Science',
                'badge_text' => 'Career Starter',
                'slug' => 'advanced-computer-diploma',
                'category_slug' => 'computer-classes',
                'description' => 'Need computer confidence for study, office work, or job applications? This diploma builds practical command over documents, Excel, presentations, databases, email, and daily digital workflows so learners can perform in real office situations.',
                'course_outline' => "Computer fundamentals\nWindows productivity\nAdvanced Word\nExcel formulas and reporting\nPowerPoint presentations\nMS Access basics\nEmail and internet workflow\nProfessional document handling",
                'photo' => 'site/img/computer-diploma.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '10 Seats',
                'duration' => '3 Months',
                'instructor' => 'Surendra Bhattarai',
                'is_featured' => true,
                'meta_keywords' => 'computer diploma Pokhara, computer course Nepal',
            ],
            [
                'name' => 'Office and Admin Skills Package',
                'badge_text' => 'Office Skills',
                'slug' => 'corporate-office-package',
                'category_slug' => 'computer-classes',
                'description' => 'Applying for office, admin, front desk, or support roles? This package helps learners practice Word, Excel, PowerPoint, email, and file-management skills used in daily office work.',
                'course_outline' => "MS Word documentation\nExcel data handling\nPowerPoint presentation design\nEmail etiquette\nCloud collaboration\nOffice file management\nWorkplace digital habits",
                'photo' => 'site/img/computer-office-package.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '10 Seats',
                'duration' => '3 Months',
                'instructor' => 'Surendra Bhattarai',
                'is_featured' => true,
                'meta_keywords' => 'office package Pokhara, Excel class Nepal, computer skills',
            ],
            [
                'name' => 'Chinese Language Starter',
                'badge_text' => 'New Language',
                'slug' => 'chinese-language-course',
                'category_slug' => 'language-classes',
                'description' => 'Curious about Chinese for study, work, travel, or business communication? This starter course introduces pronunciation, vocabulary, basic conversation, listening, and cultural etiquette in a beginner-friendly format.',
                'course_outline' => "Chinese pronunciation\nBasic vocabulary\nListening practice\nReading basics\nSpeaking drills\nCultural etiquette\nMock conversations",
                'photo' => 'site/img/chinese-course.jpg',
                'price' => 'Rs. 15,000',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => '15 Seats',
                'duration' => '1 Month',
                'instructor' => 'Chham Maya Rai',
                'is_featured' => false,
                'meta_keywords' => 'Chinese language Pokhara, Mandarin class Nepal',
            ],
            [
                'name' => 'Course Guidance Before Enrollment',
                'badge_text' => 'Guidance First',
                'slug' => 'free-course-roadmap-help',
                'category_slug' => 'other-classes',
                'description' => 'Not sure what to study next? Share your goal, current level, budget, and preferred timing so students, parents, job seekers, and abroad applicants can compare options before enrollment.',
                'course_outline' => "Goal diagnosis\nCurrent level review\nCourse comparison\nStudy abroad or job path guidance\nTimeline planning\nRecommended next step\nFollow-up contact plan",
                'photo' => 'site/img/cat-4.jpg',
                'price' => 'Free',
                'rating_star' => '0',
                'rating_count' => '0',
                'capacity' => 'Guidance Call',
                'duration' => '30 Minutes',
                'instructor' => 'Course Help Team',
                'is_featured' => true,
                'meta_keywords' => 'free course help Pokhara, course guidance Nepal, career guidance',
            ],
        ];

        foreach ($courses as $index => $courseData) {
            $category = $categories->get($courseData['category_slug']);

            $courseData['category_id'] = $category?->id;
            $courseData['category'] = $category?->name ?? 'Course Guidance and Events';
            $courseData['category_slug'] = $category?->slug ?? 'other-classes';
            $courseData['status'] = 'active';
            $courseData['meta_title'] = $courseData['name'].' | GoldenEye Academy';
            $courseData['display_order'] = ($index + 1) * 10;
            $courseData['meta_description'] = $courseData['description'];
            $courseData['aeo_summary'] = $courseData['name'].' helps learners compare fit, practice the core skills, and understand the next step before enrollment.';
            $courseData['schema_markup'] = json_encode([
                '@context' => 'https://schema.org',
                '@type' => 'Course',
                'name' => $courseData['name'],
                'description' => $courseData['description'],
                'provider' => [
                    '@type' => 'Organization',
                    'name' => 'GoldenEye Academy',
                ],
            ]);

            Course::updateOrCreate(
                ['slug' => $courseData['slug']],
                $courseData,
            );
        }
    }
}
