<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\CourseCategory;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = CourseCategory::all()->keyBy('slug');

        $courses = [
            [
                'name' => 'IELTS Masterclass for Band 7+',
                'badge_text' => 'Top Rated',
                'slug' => 'ielts-masterclass',
                'category_slug' => 'study-abroad-test-prep',
                'description' => 'Planning abroad but unsure how to reach your target band? This IELTS Masterclass turns confusion into a weekly score plan with mock tests, writing correction, speaking practice, and personal feedback. Best for students who want a clear route before paying for applications, documents, or visa processing.',
                'course_outline' => "IELTS format and scoring\nListening strategy and note-taking\nReading speed and accuracy\nWriting Task 1 and Task 2 structures\nSpeaking confidence labs\nWeekly mock tests and score review\nDestination and timeline planning",
                'photo' => 'site/img/ielts-preparation.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.9',
                'rating_count' => '342',
                'capacity' => '15 Seats',
                'duration' => '6 Weeks',
                'instructor' => 'Aakash Subedi',
                'is_featured' => true,
                'meta_keywords' => 'IELTS Pokhara, IELTS preparation Nepal, Band 7 IELTS',
            ],
            [
                'name' => 'PTE Elite Academic Training',
                'badge_text' => 'Fast Track',
                'slug' => 'pte-elite-training',
                'category_slug' => 'study-abroad-test-prep',
                'description' => 'Need a faster computer-based English test route? PTE Elite trains you around the actual AI-scored exam experience: templates, timing, fluency, and mock analysis. Best for Australia-focused or deadline-driven students who want precision instead of random practice.',
                'course_outline' => "PTE test interface\nAI scoring essentials\nSpeaking fluency drills\nWriting templates\nReading and listening practice\nMock test analysis\nScore improvement roadmap",
                'photo' => 'site/img/pte-preparation.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.8',
                'rating_count' => '215',
                'capacity' => '10 Seats',
                'duration' => '6 Weeks',
                'instructor' => 'Aakash Subedi',
                'is_featured' => true,
                'meta_keywords' => 'PTE Pokhara, PTE class Nepal, PTE Academic training',
            ],
            [
                'name' => 'Japanese Proficiency JLPT N5',
                'badge_text' => 'Japan Pathway',
                'slug' => 'jlpt-n5-elite',
                'category_slug' => 'language-classes',
                'description' => 'Starting your Japan journey from zero? JLPT N5 gives you the foundation: Hiragana, Katakana, basic Kanji, grammar, listening, and cultural confidence. Best for students who want structure before moving into higher JLPT levels, study pathways, or Japan work preparation.',
                'course_outline' => "Hiragana and Katakana\nN5 vocabulary and grammar\nBasic Kanji\nListening and conversation practice\nJapanese culture and etiquette\nJLPT mock preparation",
                'photo' => 'site/img/jlpt-n5.jpg',
                'price' => 'Rs. 15,000',
                'rating_star' => '4.7',
                'rating_count' => '189',
                'capacity' => '15 Seats',
                'duration' => '6 Months',
                'instructor' => 'Navaraj Thapa',
                'is_featured' => true,
                'meta_keywords' => 'JLPT N5 Pokhara, Japanese class Nepal, Japan language course',
            ],
            [
                'name' => 'Japanese Proficiency JLPT N4',
                'badge_text' => 'Language Plus',
                'slug' => 'jlpt-n4',
                'category_slug' => 'language-classes',
                'description' => 'Already know the basics but not ready for real Japanese conversations yet? JLPT N4 builds vocabulary, Kanji, grammar, reading, and listening so learners can move from memorizing scripts to understanding everyday Japanese with more confidence.',
                'course_outline' => "N4 grammar patterns\nExpanded vocabulary\nKanji practice\nReading short passages\nListening comprehension\nConversation drills\nJLPT preparation strategy",
                'photo' => 'site/img/jlpt-n4.jpg',
                'price' => 'Rs. 13,000',
                'rating_star' => '4.6',
                'rating_count' => '88',
                'capacity' => '15 Seats',
                'duration' => '3 Months',
                'instructor' => 'Navaraj Thapa',
                'is_featured' => false,
                'meta_keywords' => 'JLPT N4 Pokhara, Japanese language Nepal',
            ],
            [
                'name' => 'Professional Korean EPS-TOPIK',
                'badge_text' => 'High Success',
                'slug' => 'professional-korean-eps',
                'category_slug' => 'language-classes',
                'description' => 'Aiming for South Korea but overwhelmed by EPS-TOPIK preparation? This program gives learners a disciplined Korean study route with Hangul, high-frequency vocabulary, listening, reading, and exam-style practice for work-focused applicants.',
                'course_outline' => "Hangul foundation\nEPS vocabulary\nListening drills\nReading comprehension\nIndustry terms\nMock tests\nApplication timeline planning",
                'photo' => 'site/img/eps-topik.jpg',
                'price' => 'Rs. 18,000',
                'rating_star' => '4.8',
                'rating_count' => '276',
                'capacity' => '40 Seats',
                'duration' => '6 Months',
                'instructor' => 'Pradeep Paudel',
                'is_featured' => true,
                'meta_keywords' => 'Korean class Pokhara, EPS TOPIK Nepal, Korean language',
            ],
            [
                'name' => 'Basic Korean Course',
                'badge_text' => 'Beginner Friendly',
                'slug' => 'basic-korean-course',
                'category_slug' => 'language-classes',
                'description' => 'Want to learn Korean without feeling lost in the alphabet? This beginner course helps learners read Hangul, speak simple sentences, understand daily vocabulary, and build the base needed for culture, study, or future EPS-TOPIK preparation.',
                'course_outline' => "Hangul reading and writing\nBasic vocabulary\nSimple sentence patterns\nDaily conversation\nListening practice\nKorean culture basics",
                'photo' => 'site/img/basic-korean.jpg',
                'price' => 'Rs. 10,000',
                'rating_star' => '4.5',
                'rating_count' => '96',
                'capacity' => '40 Seats',
                'duration' => '3 Months',
                'instructor' => 'Pradeep Paudel',
                'is_featured' => false,
                'meta_keywords' => 'basic Korean Pokhara, Korean language Nepal',
            ],
            [
                'name' => 'Global English Professional Track',
                'badge_text' => 'Communication',
                'slug' => 'global-english-pro',
                'category_slug' => 'language-classes',
                'description' => 'If English is blocking your interview, presentation, class participation, or confidence, this track is built for you. Learn practical speaking, writing, correction, and presentation habits that help students and professionals communicate clearly.',
                'course_outline' => "Grammar correction\nSpeaking confidence\nPublic speaking\nProfessional writing\nInterview practice\nPresentation skills\nCross-cultural communication",
                'photo' => 'site/img/advanced-english.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.9',
                'rating_count' => '145',
                'capacity' => '15 Seats',
                'duration' => '45 Days',
                'instructor' => 'Ajay B.K.',
                'is_featured' => true,
                'meta_keywords' => 'English speaking Pokhara, professional English Nepal',
            ],
            [
                'name' => 'Basic English Foundation',
                'badge_text' => 'Foundation',
                'slug' => 'basic-english-course',
                'category_slug' => 'language-classes',
                'description' => 'Starting English again from the basics? This foundation course rebuilds grammar, vocabulary, reading, writing, listening, and everyday speaking so learners can stop guessing and start communicating with confidence.',
                'course_outline' => "English basics\nVocabulary building\nGrammar foundations\nListening comprehension\nReading practice\nWriting practice\nDaily speaking drills",
                'photo' => 'site/img/basic-english.jpg',
                'price' => 'Rs. 5,000',
                'rating_star' => '4.5',
                'rating_count' => '80',
                'capacity' => '15 Seats',
                'duration' => '45 Days',
                'instructor' => 'Ajay B.K.',
                'is_featured' => false,
                'meta_keywords' => 'basic English Pokhara, English course Nepal',
            ],
            [
                'name' => 'Professional Web Development',
                'badge_text' => 'Job Ready',
                'slug' => 'professional-web-development',
                'category_slug' => 'web-development-it-career',
                'description' => 'Want a skill you can actually show? Professional Web Development turns beginners into project builders with HTML, CSS, responsive UI, Laravel, databases, APIs, and deployment basics. Best for learners who want portfolio proof, not only theory.',
                'course_outline' => "HTML and CSS foundations\nResponsive UI basics\nLaravel MVC architecture\nRouting and middleware\nDatabase design\nAuthentication concepts\nREST API fundamentals\nLive project deployment",
                'photo' => 'site/img/basic-web-development.jpg',
                'price' => 'Rs. 24,850',
                'rating_star' => '4.9',
                'rating_count' => '128',
                'capacity' => '10 Seats',
                'duration' => '3 Months',
                'instructor' => 'Prasun Paudel',
                'is_featured' => true,
                'meta_keywords' => 'web development Pokhara, Laravel course Nepal, coding course',
            ],
            [
                'name' => 'Advanced Diploma in Computer Science',
                'badge_text' => 'Career Starter',
                'slug' => 'advanced-computer-diploma',
                'category_slug' => 'computer-classes',
                'description' => 'Need computer confidence for study, office work, or job applications? This diploma builds practical command over documents, Excel, presentations, databases, email, and daily digital workflows so learners can perform in real office situations.',
                'course_outline' => "Computer fundamentals\nWindows productivity\nAdvanced Word\nExcel formulas and reporting\nPowerPoint presentations\nMS Access basics\nEmail and internet workflow\nProfessional document handling",
                'photo' => 'site/img/computer-diploma.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.8',
                'rating_count' => '156',
                'capacity' => '10 Seats',
                'duration' => '3 Months',
                'instructor' => 'Surendra Bhattarai',
                'is_featured' => true,
                'meta_keywords' => 'computer diploma Pokhara, computer course Nepal',
            ],
            [
                'name' => 'Corporate Office and Admin Package',
                'badge_text' => 'Most Popular',
                'slug' => 'corporate-office-package',
                'category_slug' => 'computer-classes',
                'description' => 'Applying for office, admin, front desk, or support roles? This package gives job seekers the practical Word, Excel, PowerPoint, email, and file-management skills employers expect from day one.',
                'course_outline' => "MS Word documentation\nExcel data handling\nPowerPoint presentation design\nEmail etiquette\nCloud collaboration\nOffice file management\nWorkplace digital habits",
                'photo' => 'site/img/computer-office-package.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.7',
                'rating_count' => '312',
                'capacity' => '10 Seats',
                'duration' => '3 Months',
                'instructor' => 'Surendra Bhattarai',
                'is_featured' => true,
                'meta_keywords' => 'office package Pokhara, Excel class Nepal, computer skills',
            ],
            [
                'name' => 'Chinese Language Starter',
                'badge_text' => 'New Language',
                'slug' => 'chinese-language-course',
                'category_slug' => 'language-classes',
                'description' => 'Curious about Chinese for study, work, travel, or business exposure? This starter course introduces pronunciation, vocabulary, basic conversation, listening, and cultural etiquette in a beginner-safe format.',
                'course_outline' => "Chinese pronunciation\nBasic vocabulary\nListening practice\nReading basics\nSpeaking drills\nCultural etiquette\nMock conversations",
                'photo' => 'site/img/chinese-course.jpg',
                'price' => 'Rs. 15,000',
                'rating_star' => '4.7',
                'rating_count' => '60',
                'capacity' => '15 Seats',
                'duration' => '1 Month',
                'instructor' => 'Chham Maya Rai',
                'is_featured' => false,
                'meta_keywords' => 'Chinese language Pokhara, Mandarin class Nepal',
            ],
            [
                'name' => 'Free Course Roadmap Help',
                'badge_text' => 'Guidance First',
                'slug' => 'free-course-roadmap-help',
                'category_slug' => 'other-classes',
                'description' => 'Not sure what to study next? Do not guess. This free course-help chat maps your goal, current level, budget, timeline, and best-fit course so students, parents, job seekers, and abroad applicants can decide with clarity.',
                'course_outline' => "Goal diagnosis\nCurrent level review\nCourse comparison\nStudy abroad or job path guidance\nTimeline planning\nRecommended next step\nFollow-up contact plan",
                'photo' => 'site/img/cat-4.jpg',
                'price' => 'Free',
                'rating_star' => '5.0',
                'rating_count' => '94',
                'capacity' => 'Limited Slots',
                'duration' => '30 Minutes',
                'instructor' => 'Course Help Team',
                'is_featured' => true,
                'meta_keywords' => 'free course help Pokhara, course guidance Nepal, career guidance',
            ],
        ];

        foreach ($courses as $index => $courseData) {
            $category = $categories->get($courseData['category_slug']);

            $courseData['category_id'] = $category?->id;
            $courseData['category'] = $category?->name ?? 'Course Guidance and Events';
            $courseData['category_slug'] = $category?->slug ?? 'other-classes';
            $courseData['status'] = 'active';
            $courseData['meta_title'] = $courseData['name'].' | GoldenEye Academy';
            $courseData['display_order'] = ($index + 1) * 10;
            $courseData['meta_description'] = $courseData['description'];
            $courseData['aeo_summary'] = $courseData['name'].' helps learners move from interest to a practical next step through guided training at GoldenEye Academy.';
            $courseData['schema_markup'] = json_encode([
                '@context' => 'https://schema.org',
                '@type' => 'Course',
                'name' => $courseData['name'],
                'description' => $courseData['description'],
                'provider' => [
                    '@type' => 'Organization',
                    'name' => 'GoldenEye Academy',
                ],
            ]);

            Course::updateOrCreate(
                ['slug' => $courseData['slug']],
                $courseData,
            );
        }
    }
}
