<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Basic Web Development Course',
                'slug' => 'basic-web-development',
                'description' => 'Join our Basic Web Development Course designed for beginners who want to learn web development from the ground up. This course will teach you how to create websites using HTML and CSS, allowing you to design attractive and easy-to-use pages. You will also gain hands-on experience with Laravel, a powerful framework for building web applications. We will explore essential topics like how web applications work, managing data, and creating APIs. By the end of the course, you will have the skills needed to bring your ideas to life and embark on your web development journey.',
                'course_outline' => 'Introduction to web development / HTML / CSS / laravel /Introduction to MVC / Routing / Middleware / Building RESTful APIs / Project',
                'photo' => 'basic-web-development.jpg',
                'price' => 'Rs. 24,850',
                'rating_star' => '4.7',
                'rating_count' => '100',
                'capacity' => '10/class',
                'duration' => '8 Weeks',
                'instructor' => 'Prasun Paudel',
                'category' => 'computer classes',
                'category_slug' => 'computer-classes',
            ],
            [
                'name' => 'Advance Computer Course',
                'slug' => 'advance-computer-course',
                'description' => 'This diploma course provides a comprehensive introduction to the field of computer applications. It equips students with essential skills and knowledge, preparing them for a dynamic and rapidly evolving job market in technology. Students will gain hands-on experience with various software tools and learn how to effectively utilize technology in professional settings.',
                'course_outline' => ' Skills in efficient English and Nepali typing /Proficiency in advanced features of Microsoft Word, Excel and PowerPoint / Ability to design and manage databases using Microsoft Access / Basic graphic design skills using Adobe Photoshop',
                'photo' => 'computer-diploma.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.4',
                'rating_count' => '50',
                'capacity' => '10/class',
                'duration' => '3 Months',
                'instructor' => 'Surendra Bhattarai',
                'category' => 'computer classes',
                'category_slug' => 'computer-classes',
            ],
            [
                'name' => 'IELTS Preparation Course',
                'slug' => 'ielts-preparation-course',
                'description' => 'Preparing for the IELTS is an essential step for students aiming to study, work, or migrate to an English-speaking country. This course provides targeted training and practice, helping students to develop the necessary skills to exile in each section of the test, thereby boosting their confidence and performance.',
                'course_outline' => 'Overview of the test structure / Every week free Moke Test  / Listening / Reading / Writing / Speaking',
                'photo' => 'ielts-preparation.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.6',
                'rating_count' => '120',
                'capacity' => '15/class',
                'duration' => '6 Weeks',
                'instructor' => 'Aakash Subedi',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
            [
                'name' => 'PTE Preparation Course',
                'slug' => 'pte-preparation',
                'description' => 'Our PTE Preparation Course is specifically designed for students aiming to study, work, or migrate to English-speaking countries. The course focuses on enhancing language skills and test-taking strategies to help students achieve their desired scores.',
                'course_outline' => 'Introduction to PTE / Speaking / Writing / Reading /  Listening / Free weekly Mock Test',
                'photo' => 'pte-preparation.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.5',
                'rating_count' => '90',
                'capacity' => '10/class',
                'duration' => '6 Weeks',
                'instructor' => 'Aakash Subedi',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
            [
                'name' => 'Japanese Language Proficiency Test (JLPT) N5',
                'slug' => 'jlpt-n5',
                'description' => 'The Japanese Language Proficiency Test (JLPT) N5 is the beginner level of the Japanese language, designed for students who are just starting to learn. The N5 test assesses your ability to understand basic Japanese, including simple phrases, sentences, and everyday vocabulary. It covers key areas like kanji , hiragana, katakana, and basic grammar structures.',
                'course_outline' => 'Introduction to Japanese Language / Understanding Hiragana and Katakana / Basic Kanji / Everyday Vocabulary / Simple Sentence Structures / Listening Comprehension Exercises / Reading Short Texts / Conversational Practice / N5 Test Preparation Tips.',
                'photo' => 'jlpt-n5.jpg',
                'price' => 'Rs. 15,000',
                'rating_star' => '4.2',
                'rating_count' => '60',
                'capacity' => '15/class',
                'duration' => '6 Months',
                'instructor' => 'Navaraj Thapa',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
            [
                'name' => 'Japanese Language Proficiency Test (JLPT) N4',
                'slug' => 'jlpt-n4',
                'description' => 'The N4 level builds on the N5, covering more vocabulary, kanji, and grammar, allowing you to engage in simple conversations and understand basic written materials. This course focuses on mastering over 1,500 vocabulary words and 300 kanji.',
                'course_outline' => 'Understanding Everyday Conversations / Reading and Listening Comprehension / Common Grammar Patterns / Short News Reports / Advertisements / Vocabulary Building Exercises / Kanji Practice / Engaging in Simple Dialogues / N4 Test Preparation Strategies.',
                'photo' => 'jlpt-n4.jpg',
                'price' => 'Rs. 13,000',
                'rating_star' => '4.5',
                'rating_count' => '50',
                'capacity' => '15/class',
                'duration' => '3 Months',
                'instructor' => 'Navaraj Thapa',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
            [
                'name' => 'Basic Korean Course',
                'slug' => 'basic-korean-course',
                'description' => 'Our Basic Korean Course is designed for beginners who want to start learning the Korean language. This course covers essential vocabulary and basic grammar, enabling students to understand and communicate in simple Korean. With a focus on speaking and listening skills, students will gain confidence in everyday conversations and learn about Korean culture.',
                'course_outline' => 'Introduction to Hangul (Korean Alphabet) / Basic Vocabulary / Simple Sentence Structures / Common Phrases for Everyday Situations / Listening and Speaking Practice / Cultural Insights and Etiquette / Activities to Reinforce Learning.',
                'photo' => 'basic-korean.jpg',
                'price' => 'Rs. 10,000',
                'rating_star' => '4.5',
                'rating_count' => '50',
                'capacity' => '40/class',
                'duration' => '3 months',
                'instructor' => 'Pradeep Paudel',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
            [
                'name' => 'Korean Language Course (EPS-TOPIK)',
                'slug' => 'Korean-language-course',
                'description' => 'Our Korean Language Course is designed for individuals seeking to work in South Korea under the Employment Permit System (EPS). The course provides in-depth training in the Korean language, focusing on essential vocabulary and skills needed for the EPS-TOPIK test and real-world communication.',
                'course_outline' => 'Overview of EPS-TOPIK test structure / Practice listening / reading / vocabulary / grammar / and speaking skills.',
                'photo' => 'eps-topik.jpg',
                'price' => 'Rs. 18,000',
                'rating_star' => '4.4',
                'rating_count' => '70',
                'capacity' => '40/class',
                'duration' => '6 Months',
                'instructor' => 'Pradeep Paudel',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
            [
                'name' => 'Computer Office Package',
                'slug' => 'computer-office-package',
                'description' => 'Our Computer Office Package course is designed for beginners looking to enhance their skills in essential computer applications. Students will learn practical skills that can be applied in various office environments, making them more efficient and effective in their tasks.',
                'course_outline' => 'Typing in English and Nepali / Microsoft Word / Excel / PowerPoint / Email and Internet management / Printing and Scanning / Online Form Filling.',
                'photo' => 'computer-office-package.jpg',
                'price' => 'Rs. 7,000',
                'rating_star' => '4.5',
                'rating_count' => '100',
                'capacity' => '10/class',
                'duration' => '3 Months',
                'instructor' => 'Surendra Bhattarai',
                'category' => 'computer classes',
                'category_slug' => 'computer-classes',
            ],      
            [
                'name' => 'Basic English Course',
                'slug' => 'basic-english-course',
                'description' => 'Our Basic English Course is designed for individuals who are new to the English language or looking to strengthen their foundational skills. This course covers essential language components, helping students to communicate effectively in everyday situations.',
                'course_outline' => 'Introduction to English / Listening comprehension / Reading comprehension / Vocabulary and grammar / Speaking skills / Writing skills.',
                'photo' => 'basic-english.jpg',
                'price' => 'Rs. 5,000',
                'rating_star' => '4.3',
                'rating_count' => '80',
                'capacity' => '15/class',
                'duration' => '45 Days',
                'instructor' => 'Ajay B.k.',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
            [
                'name' => 'Advanced English Course',
                'slug' => 'advanced-english-course',
                'description' => 'Our Advanced English Course is designed for individuals who have a solid foundation in English and are looking to enhance their language proficiency. This course focuses on advanced topics and language use in various contexts, preparing students for professional and academic challenges.',
                'course_outline' => 'Overview of advanced English / Listening comprehension / Reading comprehension / Vocabulary and grammar / Speaking skills / Writing skills.',
                'photo' => 'advanced-english.jpg',
                'price' => 'RS. 7,000',
                'rating_star' => '4.7',
                'rating_count' => '50',
                'capacity' => '15/class',
                'duration' => '45 Days',
                'instructor' => 'Ajay B.k.',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
            // [
            //     'name' => 'German Language Course',
            //     'slug' => 'german-language-course',
            //     'description' => 'Our Advanced German Language Course is designed for individuals looking to enhance their language proficiency in German. The course includes extensive practice in all language skills, providing students with the confidence to engage in conversations and understand complex texts.',
            //     'course_outline' => 'Overview of advanced German / Listening comprehension / Reading comprehension / Vocabulary and grammar / Speaking skills / Writing skills.',
            //     'photo' => 'german-language.jpg',
            //     'price' => 'Rs. 15,000',
            //     'rating_star' => '4.7',
            //     'rating_count' => '40',
            //     'capacity' => '20/class',
            //     'duration' => '3 Months',
            //     'instructor' => 'Not Fixed',
            //     'category' => 'language classes',
            //     'category_slug' => 'language-classes',
            // ],
            [
                'name' => 'Chinese Language Course',
                'slug' => 'chinese-language-course',
                'description' => 'Basic course for learning Chinese for personal, academic, or professional purposes. This course offers a balanced approach to language learning, covering speaking, listening, reading, and writing skills, as well as cultural insights to enhance understanding and communication.',
                'course_outline' => 'Introduction to Chinese / Listening / Reading / Vocabulary and Grammar / Speaking Skills / Writing Skills / Cultural Insights / Mock Conversations.',
                'photo' => 'chinese-course.jpg',
                'price' => 'Rs. 15,000',
                'rating_star' => '4.7',
                'rating_count' => '60',
                'capacity' => '15/class',
                'duration' => '1 Month',
                'instructor' => 'Chham Maya Rai',
                'category' => 'language classes',
                'category_slug' => 'language-classes',
            ],
        ];        
        \App\Models\Courses::insert($data);
    }
}
